#!/bin/bash
# ------------------------------------------------------------------------------
# 
# File: vol
# Author: Gabriel Gonzalez
# 
# Brief: Control and display the system volume.
# 
# ------------------------------------------------------------------------------

##
# Source utilities.
##
. "commandline.sh"
. "io.sh"

# Globals
PROG="${0##*/}"
PROGDIR=$(dirname "$(readlink -f "${0}")")
DEFAULTCONTROLS=("Master" "Headphone" "Speaker")

##
# Options.
##
VERBOSE=

##
# Exit statuses.
##
STATUS_NORMAL=0
STATUS_GETOPT=1
STATUS_ARGS=2
STATUS_CONTROL=10
STATUS_SETVAL=11


##
# Control volume.
##
main()
{
    cli_options "-h|--help|Print program usage." \
                "-v|--verbose|Verbose output." \
                "-c|--control=control:|A volume control to act on." \
                "-d|--decrement|Decrement the volume level by the amount set by '-D'." \
                "-i|--increment|Increment the volume level by the amount set by '-D'." \
                "-l|--list|List all the volume controls." \
                "-m|--mute|Toggle mute." \
                "-s|--set=value:|Set the volume to the desired level. [Range: 0 - 100]." \
                "-A|--average|Print the average volume level." \
                "-D|--delta=value:|Set the amount to increment/decrement the volume. [Default: 5]" \
                "-S|--status|Print the mute status."
    if [ $# -eq 0 ]
    then
        volume_print "Master"
        exit $?
    else
        cli_parse "${@}"
    fi

    local help=$(cli_get "help")
    local control=$(cli_get "control")
    local decrement=$(cli_get "decrement")
    local increment=$(cli_get "increment")
    local list=$(cli_get "list")
    local mute=$(cli_get "mute")
    local setvalue=$(cli_get "set")
    local average=$(cli_get "average")
    local delta=$(cli_get "delta")
    local status=$(cli_get "status")

    if [ -z "${control}" ]
    then
        control="Master"
    fi
    if [ -z "${delta}" ]
    then
        delta=5
    fi

    AVERAGE=
    DELTA=5

    if [ -n "${help}" ]
    then
        usage
    elif [ -n "${set}" ]
    then
        volume_set
    elif [ -n "${increment}" ]
    then
        volume_increment
    elif [ -n "${decrement}" ]
    then
        volume_decrement
    elif [ -n "${list}" ]
    then
        volume_list_controls
    elif [ -n "${mute}" ]
    then
        volume_mute_toggle
    elif [ -n "${status}" ]
    then
        volume_mute_status
    else
        :
    fi
    exit $?
}

##
# Print the current volume level.
##
volume_print()
{
    local control="${1}"
    local average="${2}"
    local channel=
    local IFS=$'\n'

    # if [ -n "${average}" ]
    # then
    #     volume=$(get_average_volume "${control}")
    #     status=$(get_average_mute "${control}")
    #     echo "${control}: ${volume}% [${status}]"
    #     return
    # fi

    for channel in $(volume_channel_get_list "${control}")
    do
        local volume=$(volume_channel_get_volume "${control}" "${channel}")
        local mute=$(volume_channel_get_mute_status "${control}" "${channel}")
        echo "${control}: ${volume}% (${channel}) [${mute}]"
    done
}

# ******************************************************************************
# Set system volume
set_volume()
{
    local value="${1}"
    shift
    local controls=("${@}")

    # Verify integer value was inputted
    if ! is_integer "${value}"; then
        print_err "Unable to set volume: Input value is not an integer."
        exit ${STATUS_SETVAL}
    fi
    if [ ${value} -lt 0 -o ${value} -gt 100 ]; then
        print_err "Unable to set volume: Value must be between 0-100."
        exit ${STATUS_SETVAL}
    fi

    # Set volume
    for c in "${controls[@]}"; do
        amixer -q sset "${c}" "${value}%"
        print_control_volume "${c}"
    done
}

# ******************************************************************************
# Increment/decrement volume level
step_volume_level()
{
    local step="${1}"
    shift
    local controls=("${@}")
    for c in "${controls[@]}"; do
        amixer -q set "${c}" "${step}"
        print_control_volume "${c}"
    done
}

# ******************************************************************************
# Mute specified volume channel(s)
mute_volume()
{
    local channels=("${@}")
    for c in "${channels[@]}"; do
        amixer -q set "${c}" toggle 
        print_control_volume "${c}"
    done
}

# ******************************************************************************
# List volume channels
list_volume_controls()
{
    local first=true
    echo "Channels:"
    for c in "${DEFAULTCONTROLS[@]}"; do
        echo "* ${c}"
    done
}

# ******************************************************************************
# Print volume status
print_volume_status()
{
    local controls=("${@}")
    local status=
    for c in "${controls[@]}"; do
        status=off
        for s in $(volume_channel_get_mute_status "${c}"); do
            if [ "${s}" == "on" ]; then
                status="${s}"
                break
            fi
        done
        echo "${c}: ${status}"
    done
}

# ******************************************************************************
# Return average volume
get_average_volume()
{
    local control="${1}"

    # Calculate average volume
    sum=0
    num=0
    for val in $(volume_channel_get_volume "${control}"); do
        sum=$[ ${sum} + ${val} ]
        num=$[ ${num} + 1 ]
    done

    if [ ${num} -eq 0 ]; then
        echo 0
    else
        echo "$[ ${sum} / ${num} ]"
    fi
}

# ******************************************************************************
# Return average mute status
get_average_mute()
{
    local control="${1}"

    # Calculate average volume
    for status in $(volume_channel_get_mute_status "${control}"); do
        case "${status}" in
            on)
                echo on
                return
                ;;

            *) ;;
        esac
    done

    echo off
}

# ******************************************************************************
# Return specified channel(s)
get_control()
{
    local channel="${1}"

    # Determine which channel(s) to return
    case "${channel}" in
        all) echo "${DEFAULTCONTROLS[@]}" ;;
        *)
            channel=$(str_to_capital "${channel}")
            if is_control "${channel}"; then
                echo "${channel}"
            else
                print_err "Invalid channel specified."
                exit ${STATUS_CONTROL}
            fi
            ;;
    esac
}

##
# Return playback channel.
##
volume_channel_get_list()
{
    local control="${1}"
    amixer get "${control}" | grep 'Playback channels' \
        | sed -e 's/^.*.: //' -e 's/ - /\n/'
    return $?
}

##
# Return channel information.
##
volume_channel_get_info()
{
    local control="${1}"
    local channel="${2}"
    amixer get "${control}" | grep "${channel}:"
    return $?
}

##
# Return channel volume.
##
volume_channel_get_volume()
{
    local control="${1}"
    local channel="${2}"
    volume_channel_get_info  "${control}" "${channel}" \
        | sed 's/.*\[\(.*\)%\].*/\1/'
    return $?
}

##
# Return playback channel status.
##
volume_channel_get_mute_status()
{
    local control="${1}"
    local channel="${2}"
    volume_channel_get_info "${control}" "${channel}" \
        | sed 's/.*\[\(.*\)\]/\1/'
}

# ******************************************************************************
# Check if control exists
is_control()
{
    local channel="${1}"
    if [ -z "${channel}" ]; then
        return 1
    fi

    local exists=$(amixer | grep "control" | grep "${channel}")
    if [ -z "${exists}" ]; then
        return 1
    fi
    return 0
}

# ******************************************************************************
# Check if mulitple arguments were used when they should not have
check_multi_arg()
{
    case "${1}" in
        PRINT)
            if [ -n "${SET}" -o -n "${INCREMENT}" -o -n "${DECREMENT}" \
                -o -n "${MUTE}" -o -n "${LIST}" -o -n "${AVERAGE}" \
                -o -n "${STATUS}" ]
            then
                print_err "Unable to print volume level: Must specify only one option."
                exit ${STATUS_ARGS}
            fi
            ;;

        SET)
            if [ -n "${PRINT}" -o -n "${INCREMENT}" -o -n "${DECREMENT}" \
                -o -n "${MUTE}" -o -n "${LIST}" -o -n "${AVERAGE}" \
                -o -n "${STATUS}" ]
            then
                print_err "Unable to set volume level: Must specify only one option."
                exit ${STATUS_ARGS}
            fi
            ;;

        INCREMENT)
            if [ -n "${PRINT}" -o -n "${SET}" -o -n "${DECREMENT}" \
                -o -n "${MUTE}" -o -n "${LIST}" -o -n "${AVERAGE}" \
                -o -n "${STATUS}" ]
            then
                print_err "Unable to increment volume level: Must specify only one option."
                exit ${STATUS_ARGS}
            fi
            ;;

        DECREMENT)
            if [ -n "${PRINT}" -o -n "${SET}" -o -n "${INCREMENT}" \
                -o -n "${DECREMENT}" -o -n "${MUTE}" -o -n "${LIST}" \
                -o -n "${AVERAGE}" -o -n "${STATUS}" ]
            then
                print_err "Unable to decrement volume level: Must specify only one option."
                exit ${STATUS_ARGS}
            fi
            ;;

        MUTE)
            if [ -n "${PRINT}" -o -n "${SET}" -o -n "${INCREMENT}" \
                -o -n "${DECREMENT}" -o -n "${LIST}" -o -n "${AVERAGE}" \
                -o -n "${STATUS}" ]
            then
                print_err "Unable to toggle mute: Must specify only one option."
                exit ${STATUS_ARGS}
            fi
            ;;

        LIST)
            if [ -n "${PRINT}" -o -n "${SET}" -o -n "${INCREMENT}" \
                -o -n "${DECREMENT}" -o -n "${MUTE}" -o -n "${AVERAGE}" \
                -o -n "${STATUS}" ]
            then
                print_err "Unable to list volume channels: Must specify only one option."
                exit ${STATUS_ARGS}
            fi
            ;;

        AVERAGE)
            if [ -n "${PRINT}" -o -n "${SET}" -o -n "${INCREMENT}" \
                -o -n "${DECREMENT}" -o -n "${MUTE}" -o -n "${LIST}" \
                -o -n "${STATUS}" ]
            then
                print_err "Unable to print average volume: Must specify only one option."
                exit ${STATUS_ARGS}
            fi
            ;;

        STATUS)
            if [ -n "${PRINT}" -o -n "${SET}" -o -n "${INCREMENT}" \
                -o -n "${DECREMENT}" -o -n "${MUTE}" -o -n "${LIST}" \
                -o -n "${AVERAGE}" ]
            then
                print_err "Unable to print volume status: Must specify only one option."
                exit ${STATUS_ARGS}
            fi
            ;;

        *)
            ;;
    esac
}

# ******************************************************************************
# Run script
main "${@}"
